#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [[ "$1" == "--help" ]] || [[ "$1" == "-help" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "-?" ]]
then
    echo "Some help text"
    exit 0
fi

HOST=$1
if [[ "$HOST" == "" ]]
then
    echo "Please pass a host"
    exit 1
fi

if [ "${2-}" == "" ]
then
    PORT=22
else
    PORT=$2
fi

echo "Checking $HOST"
until nc -vzw 2 "$HOST" "$PORT"; 
    do sleep 2; 
done

exit 0
